Job_roles = ("Backend Developer", "Backend Developer Intern", "Biomedical Engineer", "Biomedical Engineering Intern", 
 "Business Analyst", "Business Analyst Intern", "Business Development Manager", "Business Development Intern", 
 "Cloud Engineer", "Cloud Engineering Intern", "Content Writer", "Content Writing Intern", 
 "Customer Insights Analyst", "Customer Insights Intern", "Customer Success Manager", "Customer Success Intern", 
 "Customer Support Specialist", "Customer Support Intern", "Cybersecurity Analyst", "Cybersecurity Intern", 
 "Data Analyst", "Data Analyst Intern", "Data Engineer", "Data Engineering Intern", 
 "Data Scientist", "Data Science Intern", "Database Administrator", "Database Administration Intern", 
 "DevOps Engineer", "DevOps Intern", "Digital Marketing Specialist", "Digital Marketing Intern", 
 "E-commerce Specialist", "E-commerce Intern", "Electrical Engineer", "Electrical Engineering Intern", 
 "Financial Analyst", "Financial Analyst Intern", "Frontend Developer", "Frontend Developer Intern", 
 "Full Stack Developer", "Full Stack Developer Intern", "Graphic Designer", "Graphic Design Intern", 
 "Human Resources Manager", "Human Resources Intern", "IT Support Specialist", "IT Support Intern", 
 "Information Security Specialist", "Information Security Intern", "Machine Learning Engineer", 
 "Machine Learning Intern", "Mechanical Engineer", "Mechanical Engineering Intern", 
 "Network Administrator", "Network Administration Intern", "Operations Manager", "Operations Intern", 
 "Product Manager", "Product Management Intern", "Project Manager", "Project Management Intern", 
 "Quality Assurance Engineer", "Quality Assurance Intern", "Research Scientist", "Research Intern", 
 "Sales Engineer", "Sales Engineering Intern", "Sales Representative", "Sales Intern", 
 "SEO Specialist", "SEO Intern", "Social Media Manager", "Social Media Intern", 
 "Software Engineer", "Software Engineering Intern", "Software Tester", "Software Testing Intern", 
 "Solutions Architect", "Solutions Architect Intern", "Supply Chain Analyst", "Supply Chain Intern", 
 "Systems Engineer", "Systems Engineering Intern", "Technical Support Engineer", "Technical Support Intern", 
 "UI/UX Designer", "UI/UX Design Intern", "Video Editor", "Video Editing Intern", 
 "Web Developer", "Web Development Intern")
