Skillset = ("Python", "Java", "JavaScript", "C++", "C#", "SQL", "HTML", "CSS", "React", "Angular", 
 "Node.js", "Express.js", "Django", "Flask", "Ruby on Rails", "PHP", "Swift", "Kotlin", 
 "Objective-C", "Go", "TypeScript", "MATLAB", "R", "Scala", "Perl", "Hadoop", "Spark", 
 "Kafka", "Tableau", "Power BI", "TensorFlow", "Keras", "PyTorch", "Scikit-Learn", 
 "Pandas", "NumPy", "Machine Learning", "Deep Learning", "Natural Language Processing (NLP)", 
 "Computer Vision", "Data Analysis", "Data Visualization", "Big Data", "Database Management", 
 "MySQL", "PostgreSQL", "MongoDB", "Firebase", "Oracle Database", "AWS", "Microsoft Azure", 
 "Google Cloud Platform (GCP)", "DevOps", "Docker", "Kubernetes", "Jenkins", "CI/CD", 
 "Git", "GitHub", "GitLab", "Bitbucket", "Agile Methodologies", "Scrum", "JIRA", 
 "Linux", "Unix", "Windows Server", "Shell Scripting", "Network Security", "Cybersecurity", 
 "Penetration Testing", "Blockchain", "Smart Contracts", "Cryptography", "Augmented Reality (AR)", 
 "Virtual Reality (VR)", "Cloud Computing", "Edge Computing", "Internet of Things (IoT)", 
 "3D Modeling", "UI/UX Design", "Adobe XD", "Figma", "Sketch", "AutoCAD", "SolidWorks", 
 "Systems Architecture", "Embedded Systems", "Microcontrollers", "VLSI Design", "FPGA", 
 "Quantum Computing", "Salesforce", "SAP", "Microsoft Dynamics", "Project Management", 
 "Risk Management", "Business Analysis", "Data Mining", "Ethical Hacking", "SEO", 
 "Digital Marketing", "Content Management Systems (CMS)", "WordPress", "Magento", "Shopify")
